[package]
name = "wingc-cli"
version = "0.1.0"
edition = "2024"
default-run = "wingc"

[dependencies]
argh = "0.1.13"
miette = { version = "7.5.0", features = ["fancy"] }
wingc = { version = "0.1.0", path = "../wingc" }

[[bin]]
name="wingc"
path="src/main.rs"
