document = { (WHITESPACE* ~ (struct | enum))+ ~ WHITESPACE* }

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

SEP = _{";" | "," }

ident = {(LETTER | NUMBER)+}
type = {ident | ("["~ type ~ "]")}

struct_field = {ident ~ ":" ~ type}
struct_body = {
    "{" ~ struct_field ~ (SEP ~ struct_field)* ~ (SEP)? ~ "}" |   
    "{" ~ "}"
}
struct = {"struct" ~ ident ~ struct_body}

enum_body = {
    "{" ~ type ~ (SEP ~ type)* ~ "}" |
    "{" ~ "}"   
}
enum = { "enum" ~ ident ~ enum_body }
